server:
  port: 8080
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: tjdtn
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp